# IMAGES 
ui.splash.image = /UserInterface_Component/Resource/Image/SplashArt.png
ui.icon.image = /UserInterface_Component/Resource/Icon/Icon.png

# TEXT 
app.name = CHECKLYN
app.login = LOGIN

# FONTS
font.family = Helvetica

# COLORS 
color.primary = #1EC8FF
color.primary.hover = #3294b1
color.background = #0B1C2D
color.panel = #112B45
color.panel.hover = #183756
color.text.primary = #FFFFFF
color.text.secondary = #3b454f