# Database
db.File=jdbc:sqlite:Storage/DataBase/asistencia_db.sqlite

# Logs
df.logFile=Storage/Logs/AppErrors.log

# Resource
res.img.Main=/Infraestructure_Component/Resources/img/
res.img.Icon=/Infraestructure_Component/Resources/Icon/Icon.png
res.img.Splash=/Infraestructure_Component/Resources/img/SplashArt.png

# TEXT 
app.name=CHECKLYN
app.login=LOGIN

# FONTS
font.family=Helvetica

# COLORS 
color.primary = #1EC8FF
color.primary.hover = #16A6CC
color.secondary = #6EC6FF
color.secondary.hover = #5AB0E0
color.accent = #1AB394
color.accent.hover = #33B5E6
color.background = #0B1C2D
color.panel = #112B45
color.panel.hover = #1A395C
color.text.primary = #ffffff
color.text.secondary = #3b454f
color.border = #1B2A38
color.success = #2E8B57
color.error = #D9534F
color.warning = #BFA145


